package dev.upyet.evidence.domain

enum class EvidenceErrorCode {
    PERMISSION_DENIED,
    CAMERA_UNAVAILABLE,
    CAMERA_IN_USE,
    INITIALIZATION_FAILED,
    RECORDING_START_FAILED,
    FINALIZATION_FAILED,
    STORAGE_ERROR,
    DIRECT_BOOT_UNAVAILABLE,
    INTERRUPTED,
    EVIDENCE_DISABLED,
    UNKNOWN,
}
